on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
    env:
      PROJECT_NAME: np-sink
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=${{ env.PROJECT_NAME }}
      - name: Upload secrets
        run: |
          jq -n --arg NUXT_SITE_TOKEN ${{ secrets.NUXT_SITE_TOKEN }} --arg NUXT_CF_ACCOUNT_ID ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} --arg NUXT_CF_API_TOKEN ${{ secrets.CLOUDFLARE_ANALYTIC_API_TOKEN }} '{"NUXT_SITE_TOKEN":$NUXT_SITE_TOKEN, "NUXT_CF_ACCOUNT_ID":$NUXT_CF_ACCOUNT_ID, "NUXT_CF_API_TOKEN":$NUXT_CF_API_TOKEN}' > env_vars.json
          npx wrangler pages secret bulk --project-name=${{ env.PROJECT_NAME }} < env_vars.json
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
